[package]
name = "verify_signature"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reddsa = "0.3.0"
hex = "0.4.3"
pasta_curves = "0.4.0"
